source 'https://rubygems.org'

gem 'rails', '3.2.5'
gem 'omniauth'
gem 'omniauth-openid'
gem 'devise'
gem 'jquery-rails'
gem 'mysql2'

gem 'unicorn'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'launchy'
  gem 'guard'
  gem 'guard-rspec'
  gem 'growl'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'capistrano'
